version: '3'
name: zeppelin-issues-dev
volumes:
  home: {}
  database: {}
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD?:Missing MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: zeppelin-issues
      MYSQL_USER: zeppelin-issues
      MYSQL_PASSWORD: ${MYSQL_PASSWORD?:Missing MYSQL_PASSWORD}
    ports:
      - ${DEV_MYSQL_HOST_PORT:?Missing DEV_MYSQL_HOST_PORT}:3306
    volumes:
      - database:/var/lib/mysql
    command: --authentication-policy=mysql_native_password

  devenv:
    build:
      context: ./docker/development/devenv
      args:
        DEV_SSH_PASSWORD: ${DEV_SSH_PASSWORD:?Missing DEV_SSH_PASSWORD}
        DEV_UID: ${DEV_UID:-1000}
    ports:
      - "${DEV_WEB_PORT:?Missing DEV_WEB_PORT}:${DEV_WEB_PORT}"
      - "${DEV_SSH_PORT:?Missing DEV_SSH_PORT}:22"
    volumes:
      - home:/home/ubuntu
      # We mount the project in a non-root dir that's owned by the ubuntu user
      # This prevents weird errors in Next.js dev server's watcher
      - ./:/var/project/zeppelin-issues
