version: '3'
name: zeppelin-issues-dev
volumes:
  home: {}
  postgres-data: {}
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?:Missing POSTGRES_PASSWORD}
    ports:
      - ${DEV_POSTGRES_HOST_PORT:?Missing DEV_POSTGRES_HOST_PORT}:5432
    volumes:
      - postgres-data:/var/lib/postgresql

  devenv:
    build:
      context: ./docker/development/devenv
      args:
        DEV_SSH_PASSWORD: ${DEV_SSH_PASSWORD:?Missing DEV_SSH_PASSWORD}
        DEV_UID: ${DEV_UID:-1000}
    ports:
      - "${DEV_WEB_PORT:?Missing DEV_WEB_PORT}:${DEV_WEB_PORT}"
      - "${DEV_SSH_PORT:?Missing DEV_SSH_PORT}:22"
    volumes:
      - home:/home/ubuntu
      # We mount the project in a non-root dir that's owned by the ubuntu user
      # This prevents weird errors in Next.js dev server's watcher
      - ./:/var/project/zeppelin-issues
