apiVersion: v1
kind: Service
metadata:
  name: zeppelin-feedback-portal
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 3000
  selector:
    app: zeppelin-feedback-portal
