apiVersion: v1
kind: Service
metadata:
  name: zeppelin-feedback-portal
spec:
  type: LoadBalancer
  ports:
  - name: https
    port: 443
    targetPort: 3000
  selector:
    app: zeppelin-feedback-portal
